CREATE TYPE report_status AS ENUM (
  'new',
  'sent',
  'failed'
);


CREATE TABLE DW_MESSAGES
(
	ID_CODE BIGSERIAL  PRIMARY KEY,
  MESSAGE JSONB NOT NULL,
  UPSERTED_ON DATE DEFAULT CURRENT_DATE,
	status report_status DEFAULT 'new',
	sent_at TIMESTAMPTZ
);

CREATE TABLE DW_ERRORS
(
	ID_CODE BIGSERIAL  PRIMARY KEY,
  ERROR_MSG VARCHAR(1000),
	CHAT_ID BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW()

);
